### PR TITLE
Add status filter

### PR DESCRIPTION
**Pull request by henryyang42**
Add status filter by using url `GET`
- personal status: http://140.114.77.123:8000/status/?username=bruce3557
- contest status: http://140.114.77.123:8000/status/?cid=654
- problem status: http://140.114.77.123:8000/status/?pid=1007
- combined(perform `AND`): http://140.114.77.123:8000/status/?username=bruce3557&pid=1007
- provide json format: http://140.114.77.123:8000/status/?type=json

### CODE REVIEW

**Comment by nickelcheng** [comment]
+1, @bruce3557 please check
Is there any UI corresponding to combined status?

**Comment by henryyang42** [comment]
Maybe we can show filter constraint at the title.

**Comment by nickelcheng** [comment]
I mean.. Is there a button that can lead users to a combined filter status page?
Add title is a good idea.

**Comment by henryyang42** [comment]
This is supposed to be called by other apps(problem, contest).
To provide a powerful filter for user to use still has a long way to go.

**Comment by nickelcheng** [comment]
ok. However, problem and contest seems to use single filter only.
Maybe we can add more powerful filter in our apps in the future.

**Comment by henryyang42** [comment]
Definitely.

**Comment by bruce3557** [comment]
+1, going to merge

**Pull request merged**
