### PR TITLE
Fix freeze time

### PR DESCRIPTION
**Pull request by Changron**
1. fix freeze time, status and scoreboard won't show data after freeze_time if contest is not ended. If contest is ended, then show all data.
2. add button to redirect to status page to see all submission
   
3. add freeze tag

### CODE REVIEW

**Comment by nickelcheng** [comment]
Can you also add the word "freeze" in contest detail page? Just put it next to contest name.

**Comment by nickelcheng** [comment]
BTW, the pass rate means "passed user / total user".
Can you add this illustration next to "Pass Rate" title?
default

**Comment by nickelcheng** [comment]
The pass rate tooltip doesn't work now QQ

**Comment by Changron** [comment]
fixed

**Comment by nickelcheng** [comment]
+1, @bruce3557 please check

**Comment by bruce3557** [comment]
+1

**Pull request merged**
