### PR TITLE
Add buddha's protection

### PR DESCRIPTION
**Pull request by henryyang42**
```

                       _oo0oo_
                      o8888888o
                      88" . "88
                      (| -_- |)
                      0\  =  /0
                    ___/`---'\___
                  .' \\|     |# '.
                 / \\|||  :  |||# \
                / _||||| -:- |||||- \
               |   | \\\  -  #/ |   |
               | \_|  ''\---/''  |_/ |
               \  .-\__  '-'  ___/-. /
             ___'. .'  /--.--\  `. .'___
          ."" '<  `.___\_<|>_/___.' >' "".
         | | :  `- \`.;`\ _ /`;.`/ - ` : | |
         \  \ `_.   \_ __\ /__ _/   .-` /  /
     =====`-.____`.___ \_____/___.-`___.-'=====
                       `=---='


     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

               佛祖保佑         永無BUG
```

### CODE REVIEW

**Comment by nickelcheng** [comment]
XDDDDDDDD

**Comment by nickelcheng** [comment]
(裝認真) How about Christos and Allah？

**Comment by nickelcheng** [comment]
+1 besides the comment XD

**Comment by geniusgordon** [comment]
what is this XD

**Comment by henryyang42** [comment]
We will support internationalization in the future.

**Comment by bruce3557** [comment]
XD

**Comment by nickelcheng** [comment]
going to merge.

**Pull request merged**
