### PR TITLE
Release 1.0.4

### PR DESCRIPTION
**Pull request by henryyang42**
- add buddha's protection
-  add day in countdown clock
-  check permission before download special judge code
- rejudge feature
- status with permission

### CODE REVIEW

**Comment by bruce3557** [comment]
Buddha's protection will show frontend code?
will this slow down performance?

**Comment by henryyang42** [comment]
I don't know how to evaluate performance for this.

**Comment by bruce3557** [comment]
Just slow down the loading in javascript loading
Do you use any javascript compressor?

**Comment by henryyang42** [comment]
Will html commet affect js loading seriously? 
If so,  I will remove all commets in our template

**Comment by bruce3557** [comment]
OK thanks

**Comment by henryyang42** [comment]
Including the license?

**Comment by bruce3557** [comment]
License is okay.
BTW, I recommend that we can use javascript/css compressor in the future.

**Comment by henryyang42** [comment]
But buddha takes 755 chars while license takes 1073 chars QAQ

**Comment by bruce3557** [comment]
I agree that take them away

**Comment by henryyang42** [comment]
comment removed.
I will use [jsmin](https://pypi.python.org/pypi/jsmin) in the future

**Comment by bruce3557** [comment]
Ok, +1

**Pull request merged**
