### PR TITLE
Notification support html

### PR DESCRIPTION
**Pull request by henryyang42**

### CODE REVIEW

**Comment by nickelcheng** [comment]
I feel that I'm fooled QQ
Alright, I got a notification with link
screenshot from 2015-06-02 15 44 33
But after click it, it becomes
screenshot from 2015-06-02 15 44 45
The link never leads me to destination.

**Comment by henryyang42** [comment]
What link do you provide?

**Comment by henryyang42** [comment]
I have tried your link, it leads me to Google!

**Comment by henryyang42** [comment]
@drowsy810301 's ``onclick="write_content('88','True');"`` will make the link on that title lead to the popup. You have to click the link in the popup.

**Comment by bruce3557** [comment]
Need to validate the html message to prevent code injection in embedded HTML

**Comment by henryyang42** [comment]
For now, notifications come from validate source.
If we are concerned about XSS, I think edit problem has higher risk.

**Comment by bruce3557** [comment]
OK

**Comment by nickelcheng** [comment]
+1, going to merge.

**Pull request merged**
