### PR TITLE
Scoreboard for owner

### PR DESCRIPTION
**Pull request by Changron**
1. owner and coowner can see whole data even contest is frozen
2. fix freezed typo

### CODE REVIEW

**Comment by CHIAHSINHOU** [comment]
I got a syntax error

**Comment by Changron** [comment]
fix "or" in contest_info.py line 138

**Comment by bruce3557** [comment]
+1

**Comment by nickelcheng** [comment]
+1, @CHIAHSINHOU please test

**Comment by Changron** [comment]
fixed

**Comment by CHIAHSINHOU** [comment]
This PR is ok for me.

**Comment by nickelcheng** [comment]
good, going to merge

**Pull request merged**
