### PR TITLE
Move pager to utils

### LINKED ISSUE #106: Put pager into util
I found pager appears everywhere.
Is it possible to move it into util so that we can avoid duplicated code.

### PR DESCRIPTION
**Pull request by henryyang42**
Fix #106 
Move the pager template to utils to eliminate repetitive codes.

However, I found `contest.views.archive`'s pager is different from other's implementation.
Maybe @Changron can modify it in the future.

### CODE REVIEW

**Comment by nickelcheng** [comment]
How about group?

**Comment by henryyang42** [comment]
Group is fine. But that part has not been merged yet.

**Comment by nickelcheng** [comment]
I prefer Previous and Next buttons being closer.
screenshot from 2015-04-12 22 06 18

Can you put them beside ```page x of y```?
In addition, can you add two buttons: ```First``` and ```Last```?
It will be [First]  [<- Previous]  page x of y [Next ->] [Last]

**Comment by henryyang42** [comment]
By default, it  will show first page.
As for the last page, when will we need it?

**Comment by nickelcheng** [comment]
I need it when I want to debug and testing XD

**Comment by nickelcheng** [comment]
+1, I think the buttons are not important.

**Comment by nickelcheng** [comment]
going to merge

**Pull request merged**
