### PR TITLE
Add update_session_auth_hash 

### PR DESCRIPTION
**Pull request by henryyang42**
Add update_session_auth_hash  to refresh session after changing password.

### CODE REVIEW

**Comment by nickelcheng** [comment]
good!
Do you want to use @Changron's message in this PR?

**Comment by henryyang42** [comment]
No need, since it won't logout user anymore!

**Comment by nickelcheng** [comment]
I mean this "忘記密碼 update 完之後 Update successfully 字太小了 而且在最下面按鈕旁邊根本就看不到"

**Comment by henryyang42** [comment]
Yes. In the other PR.

**Comment by nickelcheng** [comment]
ok
+1, going to merge

**Pull request merged**
