### PR TITLE
Decorators

### PR DESCRIPTION
**Pull request by henryyang42**
Add some sweet decorators!

Traditionally, we have to add some nasty logic in the view.

``` py
def foo(request):
        user = validate_user(request.user)
        if user.has_judge():
            ...
```

With this, we can change it to 

``` py
@judge_auth_required
def foo(request):
    ...
```

which is prettier and the permission is clearly seen at the beginning of the view.

I'll change some other logic into decorators and refactor the code in the future.

### CODE REVIEW

**Comment by CHIAHSINHOU** [comment]
this PR is OK for me. @bruce3557  please check it

**Comment by bruce3557** [comment]
I like this PR
When to change previous code to this version?

**Comment by henryyang42** [comment]
I will change the code during my summer vacation

**Comment by bruce3557** [comment]
+1

**Pull request merged**
