### PR TITLE
Problem upload image

### PR DESCRIPTION
**Pull request by henryyang42**
https://github.com/django-ckeditor/django-ckeditor

### CODE REVIEW

**Comment by bruce3557** [comment]
Doesn't current version contain this function XD?

We talked this afternoon is for markdown usage.

**Comment by henryyang42** [comment]
Current version don't have image upload feature.
This PR can consider to be a hotfix before we support markdown or something

**Comment by bruce3557** [comment]
fine

**Comment by nickelcheng** [comment]
I got a few warning messages and an error message while ```pip install pillow```
Is that ok?
(I can runserver, though)

**Comment by nickelcheng** [comment]
BTW, I think we use 4 space indent for js files, why do you change them to 2?

**Comment by henryyang42** [comment]
You can follow this thread.
http://stackoverflow.com/questions/8915296/python-image-library-fails-with-message-decoder-jpeg-not-available-pil

**Comment by nickelcheng** [comment]
It seems different.
screenshot from 2015-05-11 23 11 52

**Comment by henryyang42** [comment]
```
sudo apt-get install python-dev
sudo pip install -I pillow
```
will work.
I have installed it on 129.

**Comment by nickelcheng** [comment]
Good! Is it necessary to list ```python-dev``` into our dependencies?

**Comment by henryyang42** [comment]
OK. I added it to README

**Comment by nickelcheng** [comment]
+1

**Pull request merged**
