### PR TITLE
Add default theme to config

### PR DESCRIPTION
**Pull request by henryyang42**
Fix `chiashin說預設theme要改Yeti`

### CODE REVIEW

**Comment by nickelcheng** [comment]
Do I need to do anything before testing? (bower had been installed)
I got this
screenshot from 2015-04-26 21 39 08

**Comment by henryyang42** [comment]
add 
```
[theme_settings]
default = yeti
``` 
in ``nthuoj.cfg`` for your ease.
Or you can delete ``nthuoj.cfg`` and reinstall again.

The same is true for #143

**Comment by nickelcheng** [comment]
ok, thanks.

**Comment by nickelcheng** [comment]
+1, going to merge

**Pull request merged**
