### PR TITLE
Bootstrapify

### PR DESCRIPTION
**Pull request by henryyang42**
Bootstrapify forms using `django-bootstrap-form` as it is suggested by @casmo888.
I also remove lots of hard code.

### CODE REVIEW

**Comment by nickelcheng** [comment]
Base on my understanding, only user pages is modified in this PR. 
Do you have any plan about using ```django-bootstrap-form``` to bootstrapify other pages? Just asking.

**Comment by nickelcheng** [comment]
+1, @bruce3557 please check this.

**Comment by henryyang42** [comment]
I fear that I will spoil their codes or result in lots of conflicts. They should add on their own.

**Comment by nickelcheng** [comment]
Ok, I'll open an issue

**Comment by bruce3557** [comment]
+1, merge this PR

**Pull request merged**
