### PR TITLE
Switch panel

### PR DESCRIPTION
**Pull request by geniusgordon**
my problem / all problem

### CODE REVIEW

**Comment by nickelcheng** [comment]
+1, @CHIAHSINHOU please test

**Comment by nickelcheng** [comment]
Can you use tab in group's fashion? 
Something like this: 
screenshot from 2015-05-27 12 03 59
It'll show the user is on which tab

**Comment by geniusgordon** [comment]
done

**Comment by nickelcheng** [comment]
going to merge.

**Pull request merged**
